### ISSUE TITLE
go-pry> panic: rpc: can't find service RPC.RPC_auto_complete

### ISSUE THREAD

**Issue by pathbox** [d4l3k/go-pry#69]
Hi,
   I try the example, but it panic

```go
[8] go-pry> panic: rpc: can't find service RPC.RPC_auto_complete

goroutine 1 [running]:
main.client_auto_complete(0xc000160240, 0xc0001c4000, 0x4768, 0x7e00, 0x7ffeefbfee14, 0x3c, 0x2428, 0x14bf5a4, 0x5, 0x14c03ef, ...)
/Users/pathbox/gowork/pkg/mod/github.com/nsf/gocode@v0.0.0-20180902125341-7b1d4e18cdc5/rpc.go:38 +0x20a
main.cmd_auto_complete(0xc000160240)
	/Users/pathbox/gowork/pkg/mod/github.com/nsf/gocode@v0.0.0-20180902125341-7b1d4e18cdc5/client.go:164 +0x38f
main.do_client(0x0)
	/Users/pathbox/gowork/pkg/mod/github.com/nsf/gocode@v0.0.0-20180902125341-7b1d4e18cdc5/client.go:44 +0x35a
main.main()
	/Users/pathbox/gowork/pkg/mod/github.com/nsf/gocode@v0.0.0-20180902125341-7b1d4e18cdc5/gocode.go:71 +0x82
```

I don't konw the relations with gocode

**Comment by pathbox** [comment]
@d4l3k Thank you, I close it, then try again

**Comment by pathbox** [comment]
@d4l3k Yeah, you are right, I close `go modules`， it runs ok.  You can think about fix it when use `go modules`

**Comment by fsubhan** [comment]
witch go modules ya
