### ISSUE TITLE
panic: failed to TypeCheck

### ISSUE THREAD

**Issue by nitrocode** [d4l3k/go-pry#71]
```
✗ echo $GOPATH
/Users/user/go
✗ go install github.com/d4l3k/go-pry
✗ go-pry run readme.go
panic: failed to TypeCheck: /Users/user/readme.go:5:6: main redeclared in this block

goroutine 1 [running]:
github.com/d4l3k/go-pry/pry.Apply(0xc0000ba280)
	/Users/user/go/src/github.com/d4l3k/go-pry/pry/pry.go:28 +0x220
main.main()
	/Users/user/xreadme.go:7 +0xf30
exit status 2
2018/11/03 22:44:23 main.go:28: exit status 1
```

Anyone know a workaround for this?

**Comment by nitrocode** [comment]
nevermind, resolved it and now getting https://github.com/d4l3k/go-pry/issues/69
