### ISSUE TITLE
seems like Doesn't Support Go 1.11 Go Module

### ISSUE THREAD

**Issue by reducm** [d4l3k/go-pry#73]
have a project using Go 1.11 Go Module with go.mod:

```bash
#file go.mod
module just-go
require(
  blah blah blah...
)
```

main file like this: 

```go
//file main.go
package main

import (
	"fmt"
	"github.com/d4l3k/go-pry/pry"
	"just-go/db"
)

func main() {
	fmt.Printf("%v\n", db.DB)
	fmt.Println("starting debug....")
	pry.Pry()
}
```

run pry

```bash
$ go-pry run main.go

2018/12/25 20:18:52 main.go:28: cannot find package "just-go/db" in any of:
        /Users/jojo/.gvm/gos/go1.11.1/src/just-go/db (from $GOROOT)
        /Users/jojo/.gvm/pkgsets/go1.11.1/global/src/just-go/db (from $GOPATH)
```

as i use the old way set the source path into GOPATH, got this:

```bash
$ ln -s just-go $GOPATH/src
$ go-pry run main.go

&{<nil> <nil> 0 0xc0000d2480 false 2 {0xc000185180} <nil> {{0 0} {<nil>} map[] 0} 0xc000118c60 0x17cde40 0xc0001c28a0 false}
starting debug....
panic: failed to TypeCheck: /Users/jojo/yiwu/just-go/tasks/debug/debug.go:5:2: could not import github.com/d4l3k/go-pry/pry (can't find import: "github.com/d4l3k/go-pry/pry")

goroutine 1 [running]:
github.com/d4l3k/go-pry/pry.Apply(0xc0001e8100)
        /Users/jojo/.gvm/pkgsets/go1.11.1/global/pkg/mod/github.com/d4l3k/go-pry@v0.0.0-20181122210047-3e3af674fe57/pry/pry.go:28 +0x220
main.main()
        /Users/jojo/yiwu/just-go/main.go:12 +0x198a
exit status 2
2018/12/25 20:21:26 main.go:28: exit status 1
```

Go Module has a new way to put the compiled pkg into the $GOPATH/pkg/mod, and no longer use the $GOPATH/src, any other idea to fix this problem ?

**Comment by denniswon** [comment]
I am having the same issue. no workaround here?

**Comment by kofj** [comment]
same question too.

**Comment by stevebaros** [comment]
Is this project dead ?

**Comment by d4l3k** [comment]
Unfortunately go modules aren't well supported by the standard library. Most of the modules/vendor implementation seems to be located in cmd/go and not exported as a usable library unlike the previous code.

As a work around you can use `GO111MODULE=off` to disable modules.

I haven't had a ton of time to dig into better support for this, PRs / suggestions on how to support modules cleanly are welcome :)

**Comment by d4l3k** [comment]
Took another pass at this and it's now working. 

```
⋊> ~/D/just-go go mod init github.com/d4l3k/just-go                                                                                                 00:10:06
go: creating new go.mod: module github.com/d4l3k/just-go
go: to add module requirements and sums:
	go mod tidy
⋊> ~/D/just-go go mod tidy                                                                                                                          00:10:11
go: finding module for package github.com/d4l3k/go-pry/pry
go: found github.com/d4l3k/go-pry/pry in github.com/d4l3k/go-pry v0.0.0-20210726070227-12ce9461a069
⋊> ~/D/just-go go-pry -d run .                                                                                                                      00:10:15
2021/07/26 00:10:22 generate.go:40: Prying into /home/rice/Developer/just-go/main.go
...
2021/07/26 00:10:22 generate.go:40:  :: Found 1 pry statements.
starting debug....

From /home/rice/Developer/just-go/main.go @ line 11 :

     6:   "github.com/d4l3k/go-pry/pry"
     7: )
     8:
     9: func main() {
    10:   fmt.Println("starting debug....")
 => 11:   pry.Pry()
    12: }
    13:

[81] go-pry> fmt.Sprintf("asdf %d", 10)
=> "asdf 10"
[82] go-pry> exit
Reverting files
⋊> ~/D/just-go ls                                                                                                                                   00:10:35
go.mod  go.sum  main.go
⋊> ~/D/just-go cat main.go                                                                                                                          00:10:39
package main

import (
	"fmt"

	"github.com/d4l3k/go-pry/pry"
)

func main() {
	fmt.Println("starting debug....")
	pry.Pry()
}
```

I had previously missed the fact that https://pkg.go.dev/golang.org/x/tools/go/packages exists. The old importer/build packages no longer wok and there's a new one instead. Switching to that resolved most of the issues w/ some work arounds on top.
