### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Integralist** [d4l3k/go-pry#9]
Hi, 

I've tried go-pry with two different projects and in both instances it would return missing dependency issues. I just want to verify that these dependencies shouldn't be handled internally by go-pry.

Below is the error I'm getting from running `pry.Pry()` in my open-source project https://github.com/integralist/Go-Requester/

```
panic: cannot find package "gopkg.in/check.v1" in any of:
        /usr/local/Cellar/go/1.5/libexec/src/gopkg.in/check.v1 (from $GOROOT)
        /Users/M/Projects/golang/src/gopkg.in/check.v1 (from $GOPATH)

goroutine 1 [running]:
main.InjectPry(0x82082cf80, 0x35, 0x0, 0x0, 0x0, 0x0)
        /Users/M/Projects/golang/src/github.com/d4l3k/go-pry/main.go:60 +0x1324
main.main.func4(0x82082cf80, 0x35, 0x88206978b8, 0x820a1a690, 0x0, 0x0, 0x0, 0x0)
        /Users/M/Projects/golang/src/github.com/d4l3k/go-pry/main.go:242 +0x1ee
path/filepath.walk(0x82082cf80, 0x35, 0x88206978b8, 0x820a1a690, 0x820bd9f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:349 +0x80
path/filepath.walk(0x820684fc0, 0x26, 0x88206978b8, 0x820695040, 0x820bd9f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x8206a66a0, 0x1e, 0x88206978b8, 0x820694ff0, 0x820bd9f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x8206a6600, 0x15, 0x88206978b8, 0x820694fa0, 0x820bd9f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x8206a6500, 0x11, 0x88206978b8, 0x820694f00, 0x820bd9f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x8206aa230, 0x6, 0x88206978b8, 0x820694e10, 0x820bd9f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x309430, 0x1, 0x88206978b8, 0x8204f3630, 0x820bd9f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.Walk(0x309430, 0x1, 0x820bd9f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:396 +0xe1
main.main()
        /Users/M/Projects/golang/src/github.com/d4l3k/go-pry/main.go:252 +0x9e0

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/Cellar/go/1.5/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/Cellar/go/1.5/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0x3895d8, 0x820514728, 0x30c978, 0x6, 0x33418, 0x2)
        /usr/local/Cellar/go/1.5/libexec/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0x820514728, 0x0, 0x18)
        /usr/local/Cellar/go/1.5/libexec/src/runtime/select.go:392 +0xa64
runtime.selectgo(0x820514728)
        /usr/local/Cellar/go/1.5/libexec/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/Cellar/go/1.5/libexec/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
        /usr/local/Cellar/go/1.5/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 7 [chan receive]:
main.main.func1(0x8204fa4e0)
        /Users/M/Projects/golang/src/github.com/d4l3k/go-pry/main.go:162 +0x4d
created by main.main
        /Users/M/Projects/golang/src/github.com/d4l3k/go-pry/main.go:164 +0x10c
```

And here is the feedback from a separate project...

```
panic: cannot find package "github.com/aws/aws-sdk-go/service/sts" in any of:
        /usr/local/Cellar/go/1.5/libexec/src/github.com/aws/aws-sdk-go/service/sts (from $GOROOT)
        /Users/M/Projects/golang/src/github.com/aws/aws-sdk-go/service/sts (from $GOPATH)

goroutine 1 [running]:
main.InjectPry(0x8204fa7e0, 0x60, 0x0, 0x0, 0x0, 0x0)
        /Users/M/Projects/golang/src/github.com/d4l3k/go-pry/main.go:60 +0x1324
main.main.func4(0x8204fa7e0, 0x60, 0x88206978b8, 0x820a09a40, 0x0, 0x0, 0x0, 0x0)
        /Users/M/Projects/golang/src/github.com/d4l3k/go-pry/main.go:242 +0x1ee
path/filepath.walk(0x8204fa7e0, 0x60, 0x88206978b8, 0x820a09a40, 0x8206f1f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:349 +0x80
path/filepath.walk(0x820a09900, 0x48, 0x88206978b8, 0x820a099a0, 0x8206f1f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x820ba0680, 0x3f, 0x88206978b8, 0x82068f950, 0x8206f1f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x8204f4840, 0x33, 0x88206978b8, 0x8204f39a0, 0x8206f1f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x8204ed260, 0x2f, 0x88206978b8, 0x8204f3950, 0x8206f1f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x8204ed140, 0x24, 0x88206978b8, 0x8204f3900, 0x8206f1f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x8204f0940, 0x20, 0x88206978b8, 0x8204f38b0, 0x8206f1f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x8204f08a0, 0x15, 0x88206978b8, 0x8204f3860, 0x8206f1f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x8204f07a0, 0x11, 0x88206978b8, 0x8204f37c0, 0x8206f1f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x8204f7f10, 0x6, 0x88206978b8, 0x8204f36d0, 0x8206f1f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x309430, 0x1, 0x88206978b8, 0x8204f3630, 0x8206f1f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.Walk(0x309430, 0x1, 0x8206f1f00, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/path/filepath/path.go:396 +0xe1
main.main()
        /Users/M/Projects/golang/src/github.com/d4l3k/go-pry/main.go:252 +0x9e0

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/Cellar/go/1.5/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/Cellar/go/1.5/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0x3895d8, 0x820514728, 0x30c978, 0x6, 0x33418, 0x2)
        /usr/local/Cellar/go/1.5/libexec/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0x820514728, 0x0, 0x18)
        /usr/local/Cellar/go/1.5/libexec/src/runtime/select.go:392 +0xa64
runtime.selectgo(0x820514728)
        /usr/local/Cellar/go/1.5/libexec/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/Cellar/go/1.5/libexec/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
        /usr/local/Cellar/go/1.5/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 7 [chan receive]:
main.main.func1(0x8204fa4e0)
        /Users/M/Projects/golang/src/github.com/d4l3k/go-pry/main.go:162 +0x4d
created by main.main
        /Users/M/Projects/golang/src/github.com/d4l3k/go-pry/main.go:164 +0x10c
```

**Comment by d4l3k** [comment]
Okay, I can definitely reproduce this issue. It's being caused by how you're handling dependencies. 

By default, when you run "go get" it skips fetching test only dependencies. If you go into the directory of your package and run
```
$ go get -t ./...
```
go-pry works just fine.

However, I'll add a check to only check *_test.go if tests are required.

**Comment by Integralist** [comment]
Hi thanks for the feedback. I've tried this on both my Go-Requester project and another project is very simply and just uses the AWS SDK and I've found in both cases if I run `go get -t` as you've suggested then include `pry.Pry()` I indeed get no errors but it also doesn't actually drop me into the pry session.

**Comment by d4l3k** [comment]
That's really interesting. 

Could you give me a few more details about 
* your go version
* operating system
* exact command used to launch go-pry

I tried your go-requester project and put pry.Pry() into the "/" route and it worked just fine when I accessed that endpoint.
